### ISSUE TITLE
V12 compatability

### ISSUE THREAD

**Issue by belkasro** [thanacus/alchemist-import#1]
any eta on V12 compatability

**Comment by SinnerZer0** [comment]
Would  the project come back, for V12 compatibility? 
It's an amazing tool!

**Comment by thanacus** [comment]
Hey folks, thanks for reaching out! I've updated the module with V12 compatibility. There were no code changes required and it should continue to operate as normal.

I'd always wondered if anyone had used this module beyond myself, so thank you!!
