### ISSUE TITLE
Even through it's on 1.0.6 version on here, and on  the Install Window, it's installing the 1.0.5 version.

### ISSUE THREAD

**Issue by SinnerZer0** [thanacus/alchemist-import#2]
Well title say it all, even through the installation tool says it's the 1.0.6, it'll end up downloading the 1.0.5 version, and whenever i try to update mods, it gives a warning asking to change the Manifest Link, but it seems that both links are equal, so it's never actually updating!

**Comment by thanacus** [comment]
@SetArk please try again with v1.0.7! I missed a few places in the manifest the number was supposed to go... :(
